version: "3.7"
services:
  db:
    image: postgres:11-alpine
    env_file: .env
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
       - "8080:8080"
    depends_on:
      - db
