version: "3.7"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8080:8080"
    depends_on:
      - "db"
